name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - master  # Trigger pipeline only for pushes to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to latest version

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4  # Updated to latest version
        with:
          node-version: '20'  # Set the Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci  # More reliable for CI environments

      # Step 4: Build the app
      - name: Build the app
        run: npm run build  # Adjust build command to your project

      # Step 5: Install Firebase Tools
      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      # Step 6: Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        run: |
          npx firebase-tools@latest deploy \
            --only hosting \
            --project cloud-tasks-8b225 \
            --token ${{ secrets.FIREBASE_TOKEN }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}