name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - master  # Trigger pipeline only for pushes to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Set the Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the app
      - name: Build the app
        run: npm run build  # Adjust build command to your project

      - name: Authenticate with Firebase using service account key
        run: npm install -g firebase-tools

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CLOUD_TASKS_8B225 }}
          channelId: live
          projectId: cloud-tasks-8b225
